import {shapeTailoredResume} from '../api/_lib/resumeQuality.js';
import test from 'node:test';
import assert from 'node:assert/strict';
import { professionCases } from './fixtures/professionCorpus.mjs';
import { candidateClaimIssues, credentialEvidenceIssues } from '../src/candidateClaims.js';
import { requirementEvidenceBoundary } from '../src/documentIntegrity.js';
import { createCoverLetterHandler } from '../api/cover-letter.js';
import { createCoverLetterPlan, updateCoverLetterParagraph, createCoverLetterExportContext, validateCoverLetterExportContext, getCoverLetterReadiness, validateCoverLetterEdit } from '../src/coverLetterModel.js';
import { sourceHistoryEntries, buildTailoringChangeLedger, buildAtsReview } from '../api/_lib/atsValidation.js';
import { buildResumeRenderPlan, createResumePackage } from '../src/resumeModel.js';
import { reviewCoverLetterWriting } from '../src/coverLetterWriting.js';
const context=c=>({baseResume:c.baseResume,resumeData:c.candidate,item:c.job,atsReview:{posting_readiness:{status:'reviewed_complete',fit_allowed:true,application_ready_allowed:true},integrity:{status:'pass'},readiness:{status:'strong_fit'},requirements:[{id:'R1',requirement:c.job.required_qualifications[0],evidence_match:'direct'}],coverage:{direct:1,missing:0,adjacent:0,transferable:0}}});
async function generate(c,raw){const handler=createCoverLetterHandler({authenticate:async()=>({user:{id:'fictional-qa'},supabase:{}}),getApiKey:()=> 'test-fixture',getOpenAIKey:()=>undefined,fetchImpl:async()=>({ok:true,json:async()=>({content:[{type:'tool_use',name:'return_evidence_first_cover_letter',input:raw}]})})});const res={statusCode:200,setHeader(){},status(s){this.statusCode=s;return this;},json(body){this.body=body;return this;}};await handler({method:'POST',headers:{authorization:'Bearer fixture'},body:{resume:c.baseResume,customJob:c.job}},res);return res;}
for(const c of professionCases){
 test(`${c.id}: truthful ${c.candidate.title} letter passes API, readiness and export context`,async()=>{
  const res=await generate(c,c.letter);assert.equal(res.statusCode,200,JSON.stringify(res.body));const ctx=context(c),plan=createCoverLetterPlan(res.body.letter,ctx);assert.equal(getCoverLetterReadiness(plan,ctx).canExport,true);assert.equal(validateCoverLetterExportContext(createCoverLetterExportContext(plan,ctx)).plan.contentHash,plan.contentHash);
 });
 if(c.probe)test(`${c.id}: unsupported consequential claim fails generation, edit and restored-draft export`,async()=>{
  const raw=structuredClone(c.letter);const para=raw.paragraphs.find(p=>p.id==='evidence');para.text=c.probe.badClaim;para.evidence_refs=c.probe.badRefs;para.requirement_refs=[c.job.required_qualifications[0]];
  assert.equal((await generate(c,raw)).statusCode,422);
  const ctx=context(c),baseline=createCoverLetterPlan(c.letter,ctx);assert.equal(updateCoverLetterParagraph(baseline,'evidence',c.probe.badClaim,ctx).ok,false);
  const restored=createCoverLetterPlan(raw,ctx);assert.equal(getCoverLetterReadiness(restored,ctx).meaningChanged,true);assert.throws(()=>createCoverLetterExportContext(restored,ctx));
 });
}
test('borrowed job tenure rejects spelled-out and numeric requirements',async()=>{const c=structuredClone(professionCases[5]);c.job.required_qualifications[0]='5 years of carpentry experience';const raw=structuredClone(c.letter);Object.assign(raw.paragraphs[1],{text:c.probe.badClaim,evidence_refs:c.probe.badRefs,requirement_refs:[c.job.required_qualifications[0]]});assert.equal((await generate(c,raw)).statusCode,422);assert.deepEqual(candidateClaimIssues('I bring five years of carpentry experience.',['Five years of carpentry experience.']),[]);});
test('metric attribution stays with its employer and its team',()=>{const c=professionCases[1],ctx=context(c),plan=createCoverLetterPlan(c.letter,ctx);assert.equal(updateCoverLetterParagraph(plan,'evidence','At Maple Home Supplies, I helped the accounts-payable team reduce invoice exceptions by 20%.',ctx).ok,false);const refs=c.candidate.experience[1].bullets;assert.deepEqual(candidateClaimIssues('At Oak Office Products, I helped the accounts-payable team reduce invoice exceptions by 20%.',refs,{candidateCorpus:c.baseResume}),[]);const r=professionCases[7];assert.ok(candidateClaimIssues(r.borrowedMetric.bad,r.borrowedMetric.refs,{candidateCorpus:r.baseResume}).length);assert.deepEqual(candidateClaimIssues("At Cedar Retail, I participated in the store team's service-improvement program; the store's complaint rate fell by 15% during the program.",r.borrowedMetric.refs,{candidateCorpus:r.baseResume}),[]);});
test('generic occupational credentials preserve state, AND/OR and level',()=>{
 for(const source of ['CPA exam preparation; certification not held','CPA certification — expired','I do not have CPA certification.','Pursuing CPA certification'])assert.ok(credentialEvidenceIssues('Current CPA certification',source).length);
 assert.deepEqual(credentialEvidenceIssues('Current CPA certification','CPA certification — active'),[]);
 assert.deepEqual(credentialEvidenceIssues('PMP or CPA certification','CPA certification'),[]);
 assert.ok(credentialEvidenceIssues('PMP and CPA certification','CPA certification').length);
 assert.ok(credentialEvidenceIssues('Current forklift certification and current First Aid certification','Forklift authorization — active').length);
 assert.deepEqual(credentialEvidenceIssues('Current forklift certification and current First Aid certification','Forklift authorization — active\nFirst Aid certification — current'),[]);
 assert.ok(credentialEvidenceIssues('Master plumber licence','Journeyperson plumbing certificate — active').length);
 assert.ok(credentialEvidenceIssues('Current First Aid certificate','First Aid certificate').length);
 assert.ok(candidateClaimIssues('I hold CPA certification and lead financial-statement preparation.',['CPA exam preparation; certification not held']).length);
});
test('observed pressure tests remain adjacent; actual leadership is accepted',()=>{assert.equal(requirementEvidenceBoundary('Lead pressure testing','Observed pressure testing under supervision.').classification,'adjacent');assert.deepEqual(candidateClaimIssues('I led pressure testing and certified installation quality.',['Led pressure testing and certified installation quality.']),[]);});
test('paragraph limit rejects full raw input, preserves saved text and rejects oversized stored drafts',async()=>{const c=professionCases[9],ctx=context(c),plan=createCoverLetterPlan(c.letter,ctx),before=JSON.stringify(plan);const input=(c.candidate.experience[0].bullets[0]+' ').repeat(42);const result=updateCoverLetterParagraph(plan,'evidence',input,ctx);assert.equal(result.ok,false);assert.match(result.message,/characters over/);assert.equal(JSON.stringify(plan),before);const raw=structuredClone(c.letter);raw.paragraphs[1].text=input;const restored=createCoverLetterPlan(raw,ctx);assert.equal(restored.paragraphs[1].text.length,input.trim().length);assert.throws(()=>createCoverLetterExportContext(restored,ctx));assert.equal((await generate(c,raw)).statusCode,422);});
test('export authorization binds employer context',()=>{const c=professionCases[1],ctx=context(c),plan=createCoverLetterPlan(c.letter,ctx);const exp=createCoverLetterExportContext(plan,ctx);assert.throws(()=>validateCoverLetterExportContext({...exp,candidateCorpus:ctx.baseResume+'\nOther employer'}),/authorization/);});
test('structured employment headers support cashier and new professions without crossing sections',()=>{const c=professionCases[7];assert.equal(sourceHistoryEntries(c.baseResume).length,2);const cashier=sourceHistoryEntries(c.baseResume).find(x=>x.role==='Cashier');assert.equal(cashier.company,'Birch Market');const source='Alex Smith\nProfessional Experience\nWatchmaker - Example Repairs | 2020 - 2026\nRepaired watches.\nEducation\nDiploma - Example College | 2018 - 2020';assert.deepEqual(sourceHistoryEntries(source).map(x=>x.role),['Watchmaker']);const review=buildAtsReview(c.candidate,c.baseResume,{});assert.equal(review.provenance_issues.length,0);});
test('keyword coverage includes credentials, education and languages in the exported document',()=>{const c=professionCases[0];const review=buildAtsReview(c.candidate,c.baseResume,{keywords:['CPA','Accounting','English']});assert.deepEqual(review.missing_keywords,[]);});
test('plain headings, front-loaded trade credentials, portfolios and volunteer paragraphs',()=>{for(const c of professionCases){const p=buildResumeRenderPlan(createResumePackage(c.candidate));assert.doesNotMatch(p.sections.map(x=>x.heading).join(' '),/Verified Tools|Verified Safety|Operations & Customer/);if(['P03','P04','P05'].includes(c.id))assert.ok(p.sections.findIndex(s=>s.id==='certifications')<p.sections.findIndex(s=>s.id==='safety'));if(['P05','P09'].includes(c.id))assert.match(p.header.contactLine,/https:\/\/example.com\//);if(c.id==='P10')assert.equal(p.sections.find(s=>s.title==='Volunteer Experience').type,'paragraph');}});
test('letter-only fragment advice does not pad a concise complete letter',()=>{const c=professionCases[0];assert.ok(reviewCoverLetterWriting(c.letter.paragraphs).issues.some(x=>x.code==='sentence_fragment'));assert.equal(reviewCoverLetterWriting([{id:'opening',purpose:'opening',text:'I prepared audit schedules and reconciled client accounts.'},{id:'closing',purpose:'closing',text:'Thank you for considering my application.'}]).status,'pass');});

test('quantity units and mixed credential status remain attached to the specific fact',()=>{assert.ok(candidateClaimIssues('I reconciled 18 client accounts for 18 clients.',['Reconciled 18 balance-sheet accounts.']).length);assert.deepEqual(credentialEvidenceIssues('PMP certification','PMP certification held; CPA exam preparation'),[]);assert.ok(credentialEvidenceIssues('CPA certification','PMP certification held; CPA exam preparation').length);});

test('paragraph length boundary is checked before whitespace normalization',()=>{const c=professionCases[9],para=createCoverLetterPlan(c.letter,context(c)).paragraphs[1];for(const length of [2399,2400,2401]){const input=para.text.padEnd(length,' ');assert.equal(validateCoverLetterEdit(input,para,context(c)).ok,length<=2400);}});

test('relevant outcomes lead the role and an active accountant credential appears near the top',()=>{const c=professionCases[0];const analysis={requirements:c.job.required_qualifications.map(requirement=>({requirement,priority:'required',evidence_match:'direct'}))};const shaped=shapeTailoredResume(c.candidate,analysis);assert.match(shaped.experience[0].bullets[0],/^Reduced/);const plan=buildResumeRenderPlan(createResumePackage(c.candidate));assert.ok(plan.sections.findIndex(s=>s.id==='certifications')<plan.sections.findIndex(s=>s.id==='skills'));});

test('profession-neutral parsing retains recognized company-first employment headings',()=>{const entries=sourceHistoryEntries('Alex Smith\nProfessional Experience\nExample Studio - Graphic Designer | 2020 - 2026\nCreated print layouts.');assert.equal(entries[0].role,'Graphic Designer');assert.equal(entries[0].company,'Example Studio');});
